name: Selenium TestNG CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Step 3: Install Xvfb (virtual display for browsers)
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      # Step 4: Run Maven Tests (your master.xml suite) with Xvfb
      - name: Run TestNG Tests with Xvfb
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" mvn clean test -Dsurefire.suiteXmlFiles=master.xml

      # Step 5: Upload Surefire Reports (TestNG Results)
      - name: Upload Surefire Report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports/

      # Step 6: Upload Allure Results (if generated)
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/

      # Step 7: Upload Extent Report
      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: reports/

