name: Maven Tests (No Browser)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B clean test

    # Upload Surefire Reports
    - name: Upload Surefire Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report
        path: target/surefire-reports/

    # Upload Allure Results
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: target/allure-results/

    # Upload Extent Report
    - name: Upload Extent Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: extent-report
        path: reports/


